### ISSUE TITLE
Создать отдельный блок variables или colors и подключать его через mustDeps

### ISSUE THREAD

**Issue by adinvadim** [bemdesign/bemdesign-components#4]

**Comment by ilyar** [comment]
это в процессе

**Comment by adinvadim** [comment]
@ilyar а как это реализуется? блок colors с модификатором theme?

**Comment by trebushuk** [comment]
Как насчет блока theme с модификатором имя-темы. В bem-components на уровне дизайна уже есть папка theme в которой лежат общие для темы изображения. Почему бы не сделать ее блоком в котором разместить общие для темы стили, переменные, миксины и функции?

**Comment by ilyar** [comment]
на все вопросы можно найти ответ посмотрев процесс в ветках:

- https://github.com/bemdesign/bemdesign-components/tree/custom_deps
- https://github.com/bemdesign/bemdesign-blocks/tree/custom_deps

**Comment by ilyar** [comment]
Решено https://github.com/bemdesign/bemdesign-components/commit/8e7346a35bdf40f3f8512dfdcfeafbde880b790d

Изменения дефолтовых значений на уровне проекта через преопределение модификатора `custom` блока `theme`, пример для цветовой схемы: `common.blocks/theme/_custom/theme_custom_color.styl` см. подробнее в [bemdesign-components/common.blocks/theme/_custom](https://github.com/bemdesign/bemdesign-components/tree/8e7346a35bdf40f3f8512dfdcfeafbde880b790d/common.blocks/theme/_custom)
